### PR TITLE
[BUG]: Fix altitude spacing error in dipole grid

### PR DESCRIPTION
**Pull request by abukowski21**
# Dipole grid did not space things out correctly

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change that fixes an issue)

Dipole grid was not spacing altitudes out correctly. Points should be spaced farther apart at high altitudes, however an indexing error made this incorrect. Indexing bug fixed & unused code is removed.

# How Has This Been Tested?

- gcc on WSL/Ubuntu.
- Plotted outputs with Python (from NetCDF files):
 
All points (ignoring longitude):
output

All points, colored by longitude:
output2

Histogram of altitude, (units Re from Earth's center):
output3

# Checklist:

- [N/A] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aaronjridley** [comment]
Ok - looking at the plots, there still seems to be something weird going on.  You can see that there are steps in the grid spacing as you go from some latitudes to other latitudes. It seems like there are "clusters" that seem to be orthogonal, but then there is a step to lower or higher latitudes, then a cluster, then step, etc.  Am I just seeing weird things?

**Comment by abukowski21** [comment]
Pretty sure this is just because it's at a relatively low resolution.  This is at nLons=36 x nLats=24 x nAlts=54

Or, think it *could* be due to the fact it's laid down symmetrically at all longitudes & mirrored across the hemispheres (before being converted to geographic). 

Might even be a combination of both! I'm putting ghost cells into the grid now so I can test more in a little bit & compare to the Python outputs.  I'll plot out the raw magnetic coordinates & the coordinates converted to geographic.

I can convert this to a draft in the meantime, I submitted this before realizing how easy it will be (*hopefully*) to put the ghost cells in

**Comment by aaronjridley** [comment]
Ok. Those particular color scales make it hard to tell what is actually happening. 

If you REALLY want to test things - you could test for orthogonality. Like, take the XYZ difference of the K+1 - K-1 (along) points and XYZ diffs of the J+1 - J-1 (lat) points and do a cross product.  In theory, this should be close to zero if it is at high enough resolution.  Anyways, we can go through this when you are done with the ghostcells...

**Comment by abukowski21** [comment]
Here are two plots. Ghost cells are done too, I'll check orthogonality and commit in a little bit...

The clumping in latitude and altitude are just artifacts, not any (unexpected) errors in the grid generation...

First plot: 
- TOP: 3D view, viewing from near the equator. Can see the longitude distribution of points. They're colored according to their index along the field line, which may or may not be useful. But the mid-latitudes don't look funny at all. Just a high density of points near the pole.
- BOTTOM: top-down view. Colored by degrees longitude (latitude) on left (right). "smearing" is from the conversion from magnetic to geographic coordinates. Points look like they're spaced as expected, to me... Weird things are happening with the colors on the right because of the order in which things are plotted, but the point distribution is what's important, I think.
4-panel



---

Second plot:

- TOP: same as above, side-on view of the 3D dipole. But colored by base latitude. Color scale makes it hard to see things near the poles clearly, but thats what the bottom is for:
- BOTTOM: Single longitude, 2D view. Colors are from single field lines, connected by black dashed line. Gap near equator is from "open" nature of all field lines, currently. But there appear to be duplicate field lines at high latitudes. Explanation below...

better_plot


## Why duplicate latitudes at high latitudes?

short answer: It's the ghost cells that went over the pole. 

Longer answer:

- It's the ghost cells that went over the pole. The fact that there are two pairs is just an artifact of the grid resolution I used. 
- I set `LatMax` to 88 degrees here and used 32 lats. Since the latitude spacing isn't linear the gap between points at high latitudes is ~10 degrees! Base latitudes are -82, -93, and -105 degrees for the last grid cell & then the two ghost cells, respectively. 
  - note how I set LatMax to 88 and the last actual grid point is not 88. The same happens in the geographic grid, and I figured it was better to be consistent 
  - Setting LatMax lower (and/or having more latitudes) lessens the extent which the ghost cells stretch over the pole
- The ghost cells are then wrapped around the pole when converted to geographic coordinates...

### Options:

If we don't want the points to go over the pole there are a couple options:

1.  Use LatMax as the maximum latitude of the ghost cells
2. If LatMax is 88 degrees, ghost cells are spaced from there to the pole (89.9 degrees or something) evenly. They they won't overlap, current grid has huge overlap[ near the poles...
3. Always end the dipole grid at 89.9 degrees baselat, then only let users specify the factor they want to stretch things by & the minimum latitude (through min_apex). 
4. Something I'm not thinking of.



## Conclusion

- I think things look OK. No unexpected "clumping" or anything. 
- I could be wrong. Let me know if you want any other plots! Or the code to make them.
- Hopefully this all makes sense...

**Comment by aaronjridley** [comment]
Are you ok with this now?  Should I go ahead and ok this???

**Comment by abukowski21** [comment]
The dipole is functional! Been doing a few sanity checks and things are weird. I think it's due to the conversions at the end of init_mag_grid, which I haven't touched yet. 

The test was comparing the (delta) position vector from an ion grid point to the next point in the grid, in one direction at a time, in all three dimensions. None of them were *exactly* perpendicular to B... 

The problem:

1. Ion grid is initialized in magnetic coordinates
2. Magnetic coordinates are converted to geographic
3. Geographic coordinates are converted back to magnetic, **using a different method**.

I've been isolating the problem and that's all I can find. The code I've written so far is bug free and should make a grid perpendicular to B

----

Still need to add:

1. support for multiple cores 
2. the supercell at high latitudes (IDK what to do at low latitudes)
3. Cell corners & all that.

But the dipole's centers are done. We can close this and put the above list into a new PR, or keep this open and add to it.  My vote is close this, work with the current dipole, then I'll make a new PR when I have made the necessary improvements.

**Pull request merged**
