### PR TITLE
Python style update

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Updated python code to partially address #42.  It:

- Changes the directory structure to allow the creation of an Aether python module
- Breaks out many individual functions
- Added more time utilities
- Made code PEP8 compliant

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change that fixes an issue)
- New feature (non-breaking change that adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

It passes flake8 locally.  I have not fully tested the routines, because I do not have a test file.  To run the script in ipython, I recommend opening a session in the `Aether` main directory:

```
import aetherpy
run aetherpy/run_plot_model_results.py
```

This will yield:
```
Usage:
/user/path/to/Git/Aether/aetherpy/run_plot_model_results.py -[flags] [filenames]
Flags:
       -help : print this message, include filename for variable names and indices
       -var=number : index of variable to plot
       -cut=alt, lat, or lon : which cut you would like
       -alt=number : alt in km or grid number (closest)
       -lat=number : latitude in degrees (closest)
       -lon=number: longitude in degrees (closest)
       -log : plot the log of the variable
       -winds : overplot winds
       -tec : plot the TEC variable
       -movie=number : provide a positive frame rate to create a movie
       -ext=str : figure or movie extension
At end, list the files you want to plot. This code should work with either GITM files (*.bin) or Aether netCDF files (*.nc)
```

You can then try the `run` command with some of the flags and/or actual filenames.

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``master``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [N/A] Add a note to ``CHANGELOG.md``, summarizing the changes

### CODE REVIEW

**Comment by aaronjridley** [comment]
I am not entirely certain how to do a review on such a massive change.  You completely rewrote this into a dramatically different system. This is fine, but it completely changes things. One of the philosophies that I really wanted to follow in this model is that people don't have to get up a steep learning curve to actually begin to use/understand the code.  By rewriting this code into such an elegant system (it is very beautiful), it makes it almost impossible to understand quickly. For example, I don't even know what the main code is called, or how I would run it.  Which code is the main code? Can I just go into the run directory and run it with a file?  How (what code do I run)? I have been using python for several years, and I don't really see clearly how to do this. 

I guess, what I am expressing here is that if you want such elegant code, there needs to be a README file that tells people how to use it, the structure of the code, and other things that make it so it is trivial to use for trivial things. Do I now have to pip install this? Can I just run it? Do I have to include it in a PYTHONPATH? Or just a PATH? If so, which sub-directories? Any? Just the main directory?  I don't know. 

We should include a small output file from Aether with a simple test.sh script which runs this code to plot a couple of variables in a couple of slices. That would help.

The code is beautiful and elegant. 

I am bad at this github review stuff, so I am unsure how to make suggestions on specific commits and stuff. I'll try to figure that out. Overall, the code is very nice.

**Comment by aburrell** [comment]
Thanks for the review @aaronjridley.  You brought up a few things that I agree need to be addressed.

- [ ] Needs a README with a minimal example
- [ ] Needs a setup file <- Yes, this can be run by putting `aetherpy` in your python path, but would be better run after installation.  Once the first directory is in your path, the `__init__.py` file brings in all of the subdirectories.
- [ ] Needs a plotting script for easy visualization <- The `run_plot_model_results.py` is still a script that takes similar command line inputs.  It's not as elegant as I would prefer, but time constraints are a thing that exists.

I would prefer to do the first two items after we've settled whether or not `aetherpy` should be a separate repository or not, since that will change where things live.  I would like it if you could test the `run_plot_model_results` script and see if it works.  

When going through to create a test script for you, I found a few bugs.  They're fixed now!  Test script is going into the modified top comment so that it doesn't get lost.

**Comment by aburrell** [comment]
Given our discussion in the last meeting, I'd like to merge this after @aaronjridley can confirm the test script at the top of the conversation works.  Then I'll start pulling this into a new repository and scope the aetherpy issues to allow student participation.

**Comment by aaronjridley** [comment]
Ok, I am finally getting to this. I am really sorry that this has taken me so long to get to.
I am 100% confused on how to actually use this. If go into the main directory, and go into python, I can "import aetherpy", but I can't "run aetherpy/run_plot_model_results.py" -> Syntax error. 
What I really want to do is run this while I am in the run directory (or the output directory). So, do a run, then go into the output directory and type run_plot_model_results.py. I would have to have this in my PATH, clearly. But, would I need the aetherpy directory in my python path or something? Do I need to install this somehow? There is no setup file, so I don't think so, but I don't see how to actually do this. Help???

**Review by aaronjridley — APPROVED** [review]
I did a run and plotted results. Everything now looks good!

**Pull request merged**
